# Site settings
title: Ori Maimon
email: orimaimon22@gmail.com
description: "Ori Maimon Personal Training"
baseurl: "/"
url: "https://ori-maimon.github.io/gym-trainer/"
include: ["_pages"]
logo: 'img/logo/'

# facebook_url: https://www.facebook.com/JazBooMPT
instagram_url: https://www.instagram.com/ori_maimonn/
whatsapp_url: https://wa.me/972584100455
address_url: https://goo.gl/maps/LWHsbBC1DGUCpS7x6
appointment_booking_url: https://koalendar.com/e/atm-enterprise
# gym_group_url: https://www.thegymgroup.com/find-a-gym/east-london-gyms/london-ilford-pioneer-point/
# google_forms_url: https://docs.google.com/forms/d/1ytBEc-LurZGO_vNCqz9k6yHh1NQXmHzpGmw-G0G6Hxk/prefill
# google_analytics_id: G-RVS79BPFKD
# calendy_url: https://calendly.com/jaz_personaltraining/15min

# Developer settings
developer_name: 
developer_webpage: 
twitter_username:
github_username:

# Build settings
markdown: kramdown
